---

mariadb_use_external_repo: true

mariadb_debian_repo: https://dlm.mariadb.com/repo
mariadb_version: 12.rolling

#mariadb_root_password: Y5FZfKXzCeOWGf4kBOiFSp6Il
#mariadb_root_password_update: true

mariadb_system_users:
  - username: root
    password: ""
    home: /root
    update: true
    ignore: true

mariadb_databases:
  - name: postfix
    collation: utf8mb4_bin
    encoding: utf8mb4

mariadb_users:
  - name: postfix
    host: "%"
    password: postfix
    priv: "postfix.*:ALL"
    encrypted: false

mariadb_config_mysqld:
  bind-address: "{{ ansible_facts.default_ipv4.address }}"
  socket: "{{ mariadb_socket }}"
  skip-external-locking:
  # Skip reverse DNS lookup of clients
  skip-name-resolve: 1
  # enable performance schema
  performance_schema: 1
  # datadir: /opt/mariadb/data
  # tmpdir: /opt/mariadb/tmp
  # log_error: /opt/mariadb/log/error.log
  # slow_query_log_file: /opt/mariadb/log/mysql-slow.log
  # log_bin: /opt/mariadb/log/mysql-bin.log
  expire_logs_days: 2
  max_connections: 20
  # replication
  server-id: "{{ mariadb_server_id }}"
  relay_log: "{{ ansible_facts.hostname }}-relay-bin"
  relay_log_index: "{{ ansible_facts.hostname }}-relay-bin.index"
  max_binlog_size: 100M

...
