#!/usr/bin/python3

# (c) 2023, Bodo Schulz <bodo@boone-schulz.de>

# BSD 2-clause (see LICENSE or https://opensource.org/licenses/BSD-2-Clause)


import json
import os
import shutil
import time

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.bodsch.core.plugins.module_utils.checksum import Checksum
from ansible_collections.bodsch.core.plugins.module_utils.directory import (
    create_directory,
)
from ansible_collections.bodsch.core.plugins.module_utils.module_results import results
from ansible_collections.bodsch.core.plugins.module_utils.template.template import (
    TemplateHandler,
)

# ----------------------------------------------------------------------

DOCUMENTATION = r"""
---
module: postfix_virtual_backends
author: Bodo 'bodsch' Schulz <bodo@boone-schulz.de>
version_added: 1.0.0

short_description: Write the postfix lookup table definitions for virtual domains.
description:
    - >-
      Writes one definition file per backend, grouped by backend type, for
      example C(<dest>/mysql/virtual_alias_maps).
    - >-
      The whole definition is checksummed under C(/var/cache/ansible/postfix),
      so an unchanged run writes nothing and fires no handler.
    - Supports check mode - the pending changes are reported but nothing is written.

options:
  backends:
    description:
      - The backend definitions, keyed by backend type (C(mysql), C(pgsql), C(ldap), ...).
      - Every definition needs a C(name) plus its database connection details.
    required: true
    type: dict
  dest:
    description: Directory the definition files are written into.
    required: true
    type: str
  force:
    description:
      - Discard the checksum cache, which makes the next run rewrite every file.
    required: false
    type: bool
    default: false
  backup:
    description: Keep a timestamped copy of a file before overwriting it.
    required: false
    type: bool
    default: false
"""

EXAMPLES = r"""
- name: write the virtual backend definitions
  bodsch.email.postfix_virtual_backends:
    dest: /etc/postfix/virtual.d
    backends:
      mysql:
        - name: virtual_alias_maps
          username: postfix
          password: "{{ vault_postfix_db_password }}"
          hosts:
            - 127.0.0.1
          dbname: postfix
          query: "SELECT goto FROM alias WHERE address='%s'"
    backup: true
"""

RETURN = r"""
changed:
    description: Whether at least one definition file was written.
    returned: always
    type: bool
result:
    description: Per file state.
    returned: always
    type: list
    elements: dict
"""

# ----------------------------------------------------------------------

TPL_BACKEND = """# generated by ansible
user     = {{ item.username }}
password = {{ item.password }}
hosts    = {{ item.hosts }}
dbname   = {{ item.dbname }}

query    =
  {{ item.query | indent(2, first=False, blank=False) }}
"""


class PostfixVirtualBackends:
    """
    Render the lookup table definitions postfix needs for virtual domains,
    one file per backend, and report per file whether it changed.
    """

    def __init__(self, module):
        """
        Initialize all needed Variables
        """
        self.module = module
        self.module.log("PostfixVirtualBackends::__init__()")

        self.dest = module.params.get("dest")
        self.backends = module.params.get("backends")
        self.force = module.params.get("force")
        self.cache_directory = "/var/cache/ansible/postfix"
        self.backup = module.params.get("backup")

    def run(self):
        """
        Write one map file per configured backend.

        The whole backend definition is checksummed first, so a run that
        changes nothing touches no file and fires no handler. With force the
        checksum cache is discarded, which makes the next run rewrite
        everything.

        Returns a result mapping with failed, changed and the per file
        state.
        """
        self.module.log("PostfixVirtualBackends::run()")

        _changed = False
        _failed = True
        _msg = "module init"

        self.checksum = Checksum(self.module)
        self.template = TemplateHandler(self.module)

        result_state = []

        if self.force and not self.module.check_mode:
            if os.path.exists(self.cache_directory):
                shutil.rmtree(self.cache_directory)

        create_directory(self.cache_directory)
        checksum_file = os.path.join(self.cache_directory, "backends")

        changed, checksum, old_checksum = self.checksum.validate(
            checksum_file=checksum_file, data=self.backends
        )

        # TODO
        # check written files!
        if not changed:
            """ """
            return dict(
                changed=False, msg="The backend configuration has not been changed."
            )

        for backend_type, backend_def in self.backends.items():
            res = {}

            self.module.log(f"  - dest: {self.dest},  backend_type: {backend_type}, backend_def: {backend_def}")

            if not self.module.check_mode:
                create_directory(os.path.join(self.dest, backend_type))

            for backend_data in backend_def:
                file_name = backend_data.get("name", None)

                if not file_name:
                    # password param should not be logged!
                    backend_data["password"] = "******"

                    # valid = False
                    msg = f"ERROR: missing 'name' for this broken backend definition: {backend_data}"

                    res["general"] = dict(failed=True, msg=msg)

                else:
                    res[file_name] = dict()

                    valid, _msg = self._validate_backend(backend_data)

                    if valid:
                        _failed, _changed, _msg = self._write_template(
                            os.path.join(self.dest, backend_type, file_name),
                            backend_data,
                        )

                        res[file_name] = dict(
                            failed=_failed, changed=_changed, msg=_msg
                        )

                    else:
                        res[file_name] = dict(failed=True, msg=_msg)

            result_state.append(res)

        _state, _changed, _failed, state, changed, failed = results(
            self.module, result_state
        )

        if not _failed and not self.module.check_mode:
            self.checksum.write_checksum(checksum_file=checksum_file, checksum=checksum)

        result = dict(changed=_changed, failed=_failed, result=result_state)

        return result

    def _validate_backend(self, backend_data):
        """
        Check one backend definition before anything is written.

        A backend needs a name and the database connection details. Missing
        pieces are collected so the message names every problem of that
        entry at once, not just the first.

        Returns (valid, msg).
        """
        self.module.log("PostfixVirtualBackends::_validate_backend(backend_data)")

        valid = False
        msg = "not validated yet"

        error_msg = []

        # self.module.log(f"    {backend}")
        file_name = backend_data.get("name", None)
        db_username = backend_data.get("username", None)
        db_password = backend_data.get("password", None)
        db_hosts = backend_data.get("hosts", None)
        db_name = backend_data.get("dbname", None)
        db_query = backend_data.get("query", None)

        if not file_name:
            error_msg.append("name")
            # password param schould not be logged!
            backend_data["password"] = "******"
            msg = f"ERROR: broken backend definition: {backend_data}"

        else:
            if not db_username:
                error_msg.append("username")
            if not db_password:
                error_msg.append("password")
            if not db_hosts:
                error_msg.append("hosts")
            if not db_name:
                error_msg.append("dbname")
            if not db_query:
                error_msg.append("query")

            if len(error_msg) > 0:
                msg = f"The variables for '{file_name}' have not been defined: "
                msg += ", ".join(error_msg)
            else:
                valid = True
                msg = None

        return (valid, msg)

    def _write_template(self, file_name, data):
        """
        Write one backend definition and say whether it changed.

        The rendered content is compared against a checksum kept in the
        cache directory, so a run that changes nothing reports changed=False
        and no handler fires. An existing file is backed up with a timestamp
        suffix when backup is on.

        Returns (changed, failed, msg).
        """
        self.module.log(f"PostfixVirtualBackends::_write_template(file_name: {file_name}, data)")

        if isinstance(data, dict):
            """
            sort data
            """
            data = json.dumps(data, sort_keys=True)
            if isinstance(data, str):
                data = json.loads(data)

        checksum_file = os.path.join(
            self.cache_directory, f"{os.path.basename(file_name)}.checksum"
        )

        changed, checksum, old_checksum = self.checksum.validate(
            checksum_file=checksum_file, data=data
        )

        if not changed:
            return False, False, "The configuration file has not been changed."

        if self.module.check_mode:
            # report the pending change, but write neither the file nor the
            # checksum - otherwise the next real run would think it is done
            return False, True, "The configuration file would be written."

        if self.backup and os.path.exists(file_name):
            _dir = os.path.dirname(file_name)
            _file = os.path.basename(file_name)
            _datetime = time.strftime("%Y%m%d-%H%M")
            backup_file = os.path.join(_dir, f"{_file}-{_datetime}")
            shutil.copy2(file_name, backup_file)

        self.template.write_template(file_name, TPL_BACKEND, data)

        self.checksum.write_checksum(checksum_file=checksum_file, checksum=checksum)

        return False, True, "The configuration file was written successfully."


# ===========================================
# Module execution.


def main():
    """
    Write the postfix virtual backend map files (mysql, pgsql, ldap, ...).
    """
    args = dict(
        backends=dict(required=True, type="dict"),
        force=dict(
            required=False,
            type="bool",
            default=False,
        ),
        dest=dict(required=True, type="str"),
        backup=dict(
            required=False,
            type="bool",
            default=False
        ),
    )

    module = AnsibleModule(
        argument_spec=args,
        supports_check_mode=True,
    )

    p = PostfixVirtualBackends(module)
    result = p.run()

    module.log(msg=f"= result: {result}")
    module.exit_json(**result)


if __name__ == "__main__":
    main()
